### ISSUE TITLE
Multiple styles

### ISSUE THREAD

**Issue by sam-lex** [d3lm/ngx-drag-to-select#52]
Hello, right now is only possible to have one styling configuration (based on the docs):  
https://github.com/d3lm/ngx-drag-to-select#overriding-sass-variables
```scss
// Example for overriding the color of the selection rectangle
$select-box-color: red;

@import "~ngx-drag-to-select/scss/ngx-drag-to-select";
```

I'm wondering if it would be possible to have multiple styles, for example:  
normal selection: blue box  
remove selection: red box

I've managed to do it like so:

style.scss
```scss
@import "~ngx-drag-to-select/scss/ngx-drag-to-select";

// Styles for Drag-To-Select : Removing
dts-select-container.removing {
  .dts-select-box {
    $removing-color: #f48fb1;
    color: $removing-color;
    background: rgba( $removing-color, 0.3 );
    border-color: currentColor;
  }
}
```
html
```html
<dts-select-container [(selectedItems)]="_sToggles" [class.removing]="_isRemoving">
  ...
</dts-select-container>
```
ts
```typescript
private _initSelection_ShiftEvents() {
  const keydown$ = fromEvent( window, 'keydown' );
  const keyup$ = fromEvent( window, 'keyup' );

  merge( keydown$, keyup$ ).pipe(
    takeUntil( this.ngUnsubscribe ),
    filter((event: KeyboardEvent) => this._isSelecting && event.key === 'Shift')
  )
  .subscribe((event: KeyboardEvent) => {
    this._isRemoving = event.shiftKey;
    this.chRef.detectChanges();
  });
}
```

With this, I can have a selection box change color whenever `shift` key is pressed, works fine in all scenarios I can think of:  
1. Hold Shift, then start drag-select
2. Start drag-select, and then hold Shift
3. While drag-selecting, hold/release shift key multiple times (box color changes immediately)

now, the only problem is that this implementation uses `.dts-select-box` class to style it. So it won't work if this happens to change in the future. Any thoughts?
